controller_list:
  - name: fake_arm_controller
    joints:
      - virtual_joint
      - alpha_joint
      - beta_joint
      - gamma_joint
      - delta_joint
      - epsilon_joint
      - zeta_joint
  - name: fake_end_effector_controller
    joints:
      []